name=MultiPCF8574
version=1.0.0
author=Jordi Orts
maintainer=Jordi Orts
sentence=Control multiple PCF8574 I2C GPIO expanders as virtual pins.
paragraph=Provides a simple interface for controlling multiple PCF8574 modules using Arduino Wire library.
category=Signal Input/Output
url=https://github.com/jorts64/MultiPCF8574
architectures=*
depends=
